name: CI Builds

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            build_cmd: xmake build -v -a x86_64
            artifact_name: linux-x86_64
          - os: windows-latest
            build_cmd: xmake f -p mingw -a x86_64 && xmake build -v
            artifact_name: windows-x86_64
          - os: macos-latest
            build_cmd: xmake build -v -a x86_64
            artifact_name: macos-x86_64

    steps:
      - uses: actions/checkout@v4

      - name: Install Windows Dependencies
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          choco install mingw -y
          Invoke-WebRequest https://github.com/xmake-io/xmake/releases/download/v2.8.7/xmake-v2.8.7.win64.zip -OutFile xmake.zip
          Expand-Archive -Path xmake.zip -DestinationPath xmake
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH
          echo "$pwd\xmake" >> $env:GITHUB_PATH

      - name: Install Ubuntu Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y meson libpcre2-dev libglib2.0-dev

      - name: Setup Xmake (non-Windows)
        if: matrix.os != 'windows-latest'
        run: |
          curl -fsSL https://xmake.io/shget.text | bash
          echo "$HOME/.xmake/bin" >> $GITHUB_PATH

      - name: Build Project
        run: ${{ matrix.build_cmd }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-latest
          path: ./build/**/*release/*